language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

before_deploy:
  - zip -r nomalBoard *
  - mkdir -p deploy
  - mv nomalBoard.zip deploy/nomalBoard.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-bot-test
    key: nomalBoard.zip
    bundle-type: zip
    application: normalBoard
    deployment-group: normalBoard-group
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - futurehwan@gmail.com